from .brain import (
    load_config,
    update_config,
    get_version,
    update_version,
    refresh,
    get_working_directory,
    change_directory,
    get_current_time,
    calculate,
    save_note,
    read_notes,
    list_files,
    find_directories,
    create_directory,
    rename_directory,
    delete_directory,
    read_file,
    create_file,
    edit_file,
    append_file,
    replace_in_file,
    git_status,
    git_diff,
    git_add,
    git_commit,
    git_fetch,
    git_pull,
    git_push,
    git_log,
    git_list_branches,
    git_switch,
    read_binary_file,
    write_binary_file,
    delete_file,
    open_file,
    open_directory,
    open_browser,
    search_web,
    read_web_page,
    get_city_distance,
    kill_process,
    shutdown_computer,
    cancel_shutdown,
    open_application,
    list_applications,
    list_open_applications,
    list_media_sessions,
    identify_playing_song,
    get_current_media)

from .notifications import (
    send_notification, schedule_notification, start_timer, list_timers,
    cancel_timer)

from .message import send_message
from .commands import execute_command
from .app_close import close_application
from .app_manager import (
    search_apps, install_app, uninstall_app, get_app_operation,
    scan_app_residues, clean_app_residue,
)
from .email_service import send_email, read_emails, delete_email

from .session_log import open_current_session_log
from .weather import get_weather, set_weather_location
from .media import (control_media, search_youtube_songs, play_youtube_song,
                    search_spotify_songs, play_spotify_song)
from .self_code import (
    get_repo_lnk, get_nora_repository, list_nora_code, read_nora_code,
    edit_nora_code, update_nora_repository)
from src.diagnostics.tools import (
    check_system_health, check_disk_health, check_security_health,
)

TOOLS = [
    close_application,
    execute_command,
    search_apps,
    install_app,
    uninstall_app,
    get_app_operation,
    scan_app_residues,
    clean_app_residue,
    check_system_health,
    check_disk_health,
    check_security_health,
    control_media,
    search_youtube_songs,
    play_youtube_song,
    search_spotify_songs,
    play_spotify_song,
    get_repo_lnk,
    get_nora_repository,
    list_nora_code,
    read_nora_code,
    edit_nora_code,
    update_nora_repository,
    get_weather,
    set_weather_location,
    open_current_session_log,
    send_message,
    send_email,
    read_emails,
    delete_email,
    send_notification,
    schedule_notification,
    start_timer,
    list_timers,
    cancel_timer,
    load_config,
    update_config,
    get_version,
    update_version,
    refresh,
    get_working_directory,
    change_directory,
    get_current_time,
    calculate,
    save_note,
    read_notes,
    list_files,
    find_directories,
    create_directory,
    rename_directory,
    delete_directory,
    read_file,
    create_file,
    edit_file,
    append_file,
    replace_in_file,
    git_status,
    git_diff,
    git_add,
    git_commit,
    git_fetch,
    git_pull,
    git_push,
    git_log,
    git_list_branches,
    git_switch,
    read_binary_file,
    write_binary_file,
    delete_file,
    open_file,
    open_directory,
    open_browser,
    search_web,
    read_web_page,
    get_city_distance,
    kill_process,
    shutdown_computer,
    cancel_shutdown,
    open_application,
    list_applications,
    list_open_applications,
    list_media_sessions,
    identify_playing_song,
    get_current_media
]
