from src.init.brain import (
    load_config,
    get_version,
    refresh,
    empty_recycle_bin,
    get_working_directory,
    change_directory,
    get_current_time,
    calculate,
    save_note,
    read_notes,
    list_files,
    find_directories,
    create_directory,
    rename_directory,
    delete_directory,
    read_file,
    create_file,
    edit_file,
    append_file,
    replace_in_file,
    git_status,
    git_diff,
    git_add,
    git_commit,
    git_fetch,
    git_pull,
    git_push,
    git_log,
    git_list_branches,
    git_switch,
    read_binary_file,
    write_binary_file,
    delete_file,
    open_file,
    open_directory,
    open_browser,
    search_web,
    read_web_page,
    get_city_distance,
    kill_process,
    shutdown_computer,
    cancel_shutdown,
    launch_steam_game,
    list_steam_games,
    find_steam_game,
    open_application,
    list_applications,
    list_open_applications,
    list_media_sessions,
    identify_playing_song,
    get_current_media,
    learn_pronunciation,
    take_screenshot)

from .config import update_config
from .notifications import (send_notification, schedule_notification,
                            start_timer, list_timers, cancel_timer)

from .message import send_message
from .commands import execute_command
from .app_close import close_application
from .app_manager import (search_apps, install_app, uninstall_app, get_app_operation,
                        scan_app_residues, clean_app_residue)

from .email_service import (
    send_email,
    read_emails,
    delete_email,
    draft_email,
    get_email_draft,
    edit_email_draft,
    send_email_draft)

from .session_log import open_current_session_log
from .weather import get_weather, set_weather_location
from .media import (control_media, search_youtube_songs, play_youtube_song,
                    search_spotify_songs, play_spotify_song,
                    search_spotify_playlists, search_spotify_albums,
                    play_spotify_album,
                    list_spotify_playlists, get_spotify_playlist_tracks,
                    play_spotify_playlist)
from .self_code import (get_repo_lnk, get_repo, list_code,
                        read_code, edit_code, update_repo)

from src.diagnostics.tools import (check_system_health, check_disk_health,
                                   check_security_health, kill_self)
from .editor import open_in_editor
from .memory.tools import remember, recall, forget, list_memories
from .desktop.clipboard import read_clipboard

TOOLS = [
    remember,
    recall,
    forget,
    list_memories,
    kill_self,
    open_in_editor,
    read_clipboard,
    close_application,
    execute_command,
    search_apps,
    install_app,
    uninstall_app,
    get_app_operation,
    scan_app_residues,
    clean_app_residue,
    check_system_health,
    check_disk_health,
    check_security_health,
    control_media,
    search_youtube_songs,
    play_youtube_song,
    search_spotify_songs,
    play_spotify_song,
    search_spotify_playlists,
    search_spotify_albums,
    play_spotify_album,
    list_spotify_playlists,
    get_spotify_playlist_tracks,
    play_spotify_playlist,
    get_repo_lnk,
    get_repo,
    list_code,
    read_code,
    edit_code,
    update_repo,
    get_weather,
    set_weather_location,
    open_current_session_log,
    send_message,
    draft_email,
    get_email_draft,
    edit_email_draft,
    send_email_draft,
    send_email,
    read_emails,
    delete_email,
    send_notification,
    schedule_notification,
    start_timer,
    list_timers,
    cancel_timer,
    load_config,
    update_config,
    get_version,
    refresh,
    empty_recycle_bin,
    get_working_directory,
    change_directory,
    get_current_time,
    calculate,
    save_note,
    read_notes,
    list_files,
    find_directories,
    create_directory,
    rename_directory,
    delete_directory,
    read_file,
    create_file,
    edit_file,
    append_file,
    replace_in_file,
    git_status,
    git_diff,
    git_add,
    git_commit,
    git_fetch,
    git_pull,
    git_push,
    git_log,
    git_list_branches,
    git_switch,
    read_binary_file,
    write_binary_file,
    delete_file,
    open_file,
    open_directory,
    open_browser,
    search_web,
    read_web_page,
    get_city_distance,
    kill_process,
    shutdown_computer,
    cancel_shutdown,
    launch_steam_game,
    list_steam_games,
    find_steam_game,
    open_application,
    list_applications,
    list_open_applications,
    list_media_sessions,
    identify_playing_song,
    get_current_media,
    learn_pronunciation,
    take_screenshot
]
